name: PyInstaller Build For Mac

on:
    push:
        branches: [master]

jobs:
    job:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.8.0'
            architecture: 'x64'
        - run: |
            python -m pip install -r requirements.txt
            python -m pip install PyInstaller
            python -m PyInstaller --name JNote --icon Icons/favicon.ico --add-data main.qml:. --add-data log.txt:. --add-data Icons:Icons --clean --windowed main.py
        - uses: actions/upload-artifact@v2
          with:
            name: MacOS-PKG
            path: /Users/runner/work/JNote/JNote/dist/JNote
        - uses: actions/download-artifact@v2
          with:
            name: MacOS-PKG
            path: /Users/runner/work/JNote/JNote/dist/JNote
