name: PyInstaller Build
on:
    push:
        branches: [master]
jobs:
    macos:
        if: "contains(toJSON(github.event.commits.*.message), '[build]')"
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8.6'
            architecture: 'x64'
        - name: Setup Virtual Environment
          run: |
            pip install virtualenv
            virtualenv buildenv
        - name: Install Dependencies
          run: |
            source buildenv/bin/activate
            python install.py
            pip install PyInstaller
        - name: Test
          run: |
            source buildenv/bin/activate
            PyInstaller --name JNote --icon icons/favicon.ico --add-data main.qml:. --add-data settings.toml:. --add-data icons:icons --clean --console main.py
            cd /Users/runner/work/JNote/JNote/dist/JNote
            ls
            open ./JNote
        - name: Clean
          run: |
            cd /Users/runner/work/JNote/JNote/
            rm -rd dist
        - name: Build
          run: |
            source buildenv/bin/activate
            PyInstaller --name JNote --icon icons/favicon.ico --add-data main.qml:. --add-data settings.toml:. --add-data icons:icons --clean --windowed main.py
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: MACOS-PKG
            path: /Users/runner/work/JNote/JNote/dist/
        - name: Download Artifact
          uses: actions/download-artifact@v1
          with:
            name: MACOS-PKG
            path: /Users/runner/work/JNote/JNote/dist/
    linux:
        if: "contains(toJSON(github.event.commits.*.message), '[build]')"
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8.6'
            architecture: 'x64'
        - name: Setup Virtual Environment
          run: |
            pip install virtualenv
            python -m virtualenv buildenv
        - name: Install Dependencies
          run: |
            source buildenv/bin/activate
            python install.py
            pip install PyInstaller
        - name: Test
          run: |
            source buildenv/bin/activate
            python -m PyInstaller --name JNote --icon icons/favicon.ico --add-data main.qml:. --add-data icons:icons --add-data settings.toml:. --clean --console --noupx main.py
            cd /home/runner/work/JNote/JNote/dist/JNote
            ./JNote
        - name: Clean
          run: |
            cd /home/runner/work/JNote/JNote/
            rm -rd dist
        - name: Build
          run: |
            source buildenv/bin/activate
            python -m PyInstaller --name JNote --icon icons/favicon.ico --add-data main.qml:. --add-data icons:icons --add-data settings.toml:. --clean --windowed --noupx main.py
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: LINUX-PKG
            path: /home/runner/work/JNote/JNote/dist/
        - name: Download Artifact
          uses: actions/download-artifact@v1
          with:
            name: LINUX-PKG
            path: /home/runner/work/JNote/JNote/dist/
