name: PyInstaller Build
on:
    push:
        branches: [master]
jobs:
    macos:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8.0'
            architecture: 'x64'
        - name: Setup Virtual Env
          run: |
            python -m pip install virtualenv
            python -m virtualenv buildenv
            source buildenv/bin/activate
        - name: Install Dependencies
          run: |
            python -m pip install -r requirements.txt
            python -m pip install PyInstaller
        - name: Build
          run: |
            python -m PyInstaller --name JNote --icon Icons/favicon.ico --add-data main.qml:. --add-data log.txt:. --add-data Icons:Icons --add-data settings.json:. --clean --windowed main.py
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: MACOS-PKG
            path: /Users/runner/work/JNote/JNote/dist/
        - name: Download Artifact
          uses: actions/download-artifact@v1
          with:
            name: MACOS-PKG
            path: /Users/runner/work/JNote/JNote/dist/
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8.0'
            architecture: 'x64'
        - name: Setup Virtual Env
          run: |
            python -m pip install virtualenv
            python -m virtualenv buildenv
            source buildenv/bin/activate
        - name: Install Dependencies
          run: |
            python -m pip install -r requirements.txt
            python -m pip install PyInstaller
        - name: Build
          run: |
            python -m PyInstaller --name JNote --icon Icons/favicon.ico --add-data main.qml:. --add-data log.txt:. --add-data Icons:Icons --add-data settings.json:. --clean --windowed main.py
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: LINUX-PKG
            path: /home/runner/work/JNote/JNote/dist/
        - name: Download Artifact
          uses: actions/download-artifact@v1
          with:
            name: LINUX-PKG
            path: /home/runner/work/JNote/JNote/dist/
