name: PyInstaller Build
on:
    push:
        branches: [master]
jobs:
    macos:
        if: "contains(toJSON(github.event.commits.*.message), '[build]')"
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8.6'
            architecture: 'x64'
        - name: Setup Virtual Environment
          run: |
            pip install virtualenv
            virtualenv buildenv
            source buildenv/bin/activate
            python install.py
            pip install PyInstaller
            PyInstaller --name JNote --icon icons/favicon.ico --add-data main.qml:. --add-data settings.toml:. --add-data icons:icons --clean --windowed main.py
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: MACOS-PKG
            path: /Users/runner/work/JNote/JNote/dist/
        - name: Download Artifact
          uses: actions/download-artifact@v1
          with:
            name: MACOS-PKG
            path: /Users/runner/work/JNote/JNote/dist/
    linux:
        if: "contains(toJSON(github.event.commits.*.message), '[build]')"
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8.6'
            architecture: 'x64'
        - name: Setup Virtual Environment
          run: |
            pip install virtualenv
            virtualenv buildenv
            source buildenv/bin/activate
            python install.py
            pip install PyInstaller
            PyInstaller --name JNote --icon icons/favicon.ico --add-data main.qml:. --add-data icons:icons --add-data settings.toml:. --clean --windowed main.py
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: LINUX-PKG
            path: /home/runner/work/JNote/JNote/dist/
        - name: Download Artifact
          uses: actions/download-artifact@v1
          with:
            name: LINUX-PKG
            path: /home/runner/work/JNote/JNote/dist/
